# get posts

GET http://localhost:3333/api/post HTTP/1.1
Content-Type: application/json

###

# get post

GET http://localhost:3333/api/post/fdb515e3-104b-46ec-951f-9c72780353e3 HTTP/1.1
Content-Type: application/json

###

# get post by user id

GET http://localhost:3333/api/post/users/u-123 HTTP/1.1
Content-Type: application/json

###

# Delete post by id

DELETE http://localhost:3333/api/post/fdb515e3-104b-46ec-951f-9c72780353e3 HTTP/1.1
Content-Type: application/json

###

# Update post by id

PATCH  http://localhost:3333/api/post/162a4756-5a60-461a-9e12-0ada6b0fb717 HTTP/1.1
Content-Type: application/json

{
    "images": ["Romanqee"]
}

###

# create post-image

POST http://localhost:3333/api/post/image HTTP/1.1
Content-Type: application/json

{
    "userId": "we dsdmsss",
    "tags": ["rsmdsasda"],
    "image": "http//crsmdsasdasss.jpg"
}

###

# create post-video

POST http://localhost:3333/api/post/video HTTP/1.1
Content-Type: application/json

{
    "userId": "we dsdmsss",
    "tags": ["rsmdsasda"],
    "title": "title", 
    "linkVideo": "http//crsmdsasdasss.ru"
}

###

# create post-text

POST http://localhost:3333/api/post/text HTTP/1.1
Content-Type: application/json

{
    "userId": "Roman",
    "tags": ["rsmdsasda"],
    "title": "title",
    "preview": "preview",
    "content": "content"

}

###

# create post-citation

POST http://localhost:3333/api/post/citation  HTTP/1.1
Content-Type: application/json

{
    "userId": "Ivan dsdmsss",
    "tags": ["rsmdsasda"],
    "citation": "Многие думают, что Lorem Ipsum - взятый с потолка псевдо-латинский набор слов,",
    "author": "Lorem"
}

###

# create post-reference

POST http://localhost:3333/api/post/reference HTTP/1.1
Content-Type: application/json

{
    "userId": "we dsdmsss",
    "tags": [],
    "reference": "http//crsmdsasdasss.ru",
    "description": "description"
}

###

# repost post

POST http://localhost:3333/api/post/repost/1554a054-dd0b-406a-be4f-f0f1cf1b6f72  HTTP/1.1
Content-Type: application/json

{
    "userId": "rom123ss"

}

###